name: test

on: [push, pull_request_target]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: test
        if: github.event.event_name == 'pull_request_target'
        run: |
          echo ${{ github.event.pull_request.number }}
          echo ${{ github.event.pull_request.head.sha }}

      - name: test
        if: github.event.event_name == 'push'
        run: |
          echo ${{ github.ref##*/ }}
          echo ${{ github.sha }}
