name: test

on: [push, pull_request_target]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: set-env
        env:
          BRANCH_NAME: 123
          COMMIT_ID: 321
        if: github.event.event_name == 'pull_request_target'

      - name: set-env
        env:
          BRANCH_NAME: 456
          COMMIT_ID: 654
        if: github.event.event_name == 'pull_request_target'

      - name: test
        run: |
          echo ${BRANCH_NAME}
          echo ${{ COMMIT_ID }}
