name: test

on: [push, pull_request_target]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: checkout
        run: echo ${{ secrets.NAME }}
